module.exports = {
  GET_PRODUCTS_BEGINS: 'GET_PRODUCTS_BEGINS',
  GET_PRODUCTS_ERROR: 'GET_PRODUCTS_ERROR',
  GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
  NEXT_HEADER_SLIDE: 'NEXT_HEADER_SLIDE',
  PREVIOUS_HEADER_SLIDE: 'PREVIOUS_HEADER_SLIDE',
  SET_HEADER_SLIDE_INDEX: 'SET_HEADER_SLIDE_INDEX',
  SET_HEADER_SLIDE_PRODUCT: 'SET_HEADER_SLIDE_PRODUCT',
  OPEN_CART: 'OPEN_CART',
  CLOSE_CART: 'CLOSE_CART',
}